ncp:
  api:
    client-id: xgagayk975
    client-secret: K7F9lqTyVK4QdM3XSEH8YzTxkqpPLSs10khYDdRD

    api-access: EIPu90VEL0CPbeOQ8e09spoUvZH2HAuv0QHfsQ6w
    api-secret: 08bwOarzGnwszRvu0kNnHx43d7w0T9FzUqTIQAB5

